theme: jekyll-theme-tactile
title: 64K BASIC
description: The BASIC programming language as it was in the beginning.
github:
  public: true
  is_project_page: true
show_downloads: true
download:
  windows: https://github.com/AE9RB/basic-lang/releases/download/0.5.0/basic-win64.zip
  macos: https://github.com/AE9RB/basic-lang/releases/download/0.5.0/basic-macos.zip
