[package]
name = "basic-lang"
version = "0.1.0"
authors = ["David Turnbull"]
license = "Apache-2.0 OR MIT"
readme = "README.md"
homepage = "http://basic-lang.org/"
repository = "https://github.com/AE9RB/basic-lang"
description = "The BASIC programming language as it was in 1978."

edition = "2018"

[profile.release]
panic = "abort"

[dependencies]
ansi_term = "0.12"
ctrlc = "3"
linefeed = "0.6"

[lib]
name = "macros"
proc-macro = true
doc = false
test = false

[[bin]]
name = "basic"
path = "src/main.rs"
doc = true
